version: "3"
   
services:
  app:
    container_name: bip-task 
    build:
      dockerfile: Dockerfile.dev
      context: .
    image: hg242322/bip-task
    command: >
      sh -c "python3 manage.py collectstatic --noinput &&
             python3 manage.py makemigrations &&
             python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"